version: '3.7'
services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - DATA_DIR=${LOCALSTACK_DATA_DIR:-/tmp/localstack/data}
    ports:
      - "4566:4566"
    volumes:
      - ./aws:/etc/localstack/init/ready.d

  order-generator:
    build:
      context: ./order-generator
    ports:
      - "5000:5000"
    depends_on:
      - localstack

